"""Update parameters in positon, email, phone in User Table

Revision ID: 3df9394a2abb
Revises: 0baaf4beb8f7
Create Date: 2026-01-22 01:17:05.287010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3df9394a2abb"
down_revision: Union[str, Sequence[str], None] = "0baaf4beb8f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "position", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "phone",
        existing_type=sa.VARCHAR(length=15),
        type_=sa.String(length=11),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "phone",
        existing_type=sa.String(length=11),
        type_=sa.VARCHAR(length=15),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "users", "position", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###
