"""task.title maxlength = 150 characters

Revision ID: 9e15cae63c0c
Revises: 3e8dae74f71c
Create Date: 2026-01-26 21:16:59.790464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e15cae63c0c"
down_revision: Union[str, Sequence[str], None] = "3e8dae74f71c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "title",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "title",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
