"""overdue fields in Tast table

Revision ID: 32baa895bb08
Revises: 9e15cae63c0c
Create Date: 2026-01-27 13:17:07.525188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32baa895bb08"
down_revision: Union[str, Sequence[str], None] = "9e15cae63c0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("overdue_notified", sa.Boolean(), nullable=True))
    op.add_column(
        "tasks",
        sa.Column("overdue_notified_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "overdue_notified_at")
    op.drop_column("tasks", "overdue_notified")
    # ### end Alembic commands ###
