"""deadline_date field added to Task Table

Revision ID: 3e8dae74f71c
Revises: 3df9394a2abb
Create Date: 2026-01-25 18:39:14.242451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e8dae74f71c"
down_revision: Union[str, Sequence[str], None] = "3df9394a2abb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("deadline_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("tasks", "content", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "content", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("tasks", "deadline_date")
    # ### end Alembic commands ###
