"""user is_verifies nullabel=False

Revision ID: 93ae448d3839
Revises: 30e97c3d299f
Create Date: 2026-02-07 23:26:53.532772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93ae448d3839"
down_revision: Union[str, Sequence[str], None] = "30e97c3d299f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
